apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: labregistry_db

---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  ConnectionStrings__Postgres: "Host=postgres-service;Port=5432;Database=labregistry_db;Username=postgres;Password=postgres"

---
apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret
type: Opaque
stringData:
  BACKEND_HOST: backend-service